/*
 * Extension Config API
 *
 * API to submit and publish an ExtensionConfig object
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
	"github.com/supabase-community/supabase-go"
)

type DefaultAPI struct {
	SupabaseClient *supabase.Client
}

// Post /api/extensions
// Submit a new extension config
func (api *DefaultAPI) CreateExtension(c *gin.Context) {
	var extension *Extension

	// Bind the JSON body to the Extension struct
	if err := c.ShouldBindJSON(&extension); err != nil {
		c.JSON(400, gin.H{"error": err.Error()})
		return
	}

	extension.createExtension()

	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK", "extension": extension})
}

func (api *DefaultAPI) GetAllExtensions(c *gin.Context) {
	c.JSON(200, getAllExtensions(api.SupabaseClient))
}
