/*
 * Extension Config API
 *
 * API to submit and publish an ExtensionConfig object
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// IndividualConfig - Generic configuration object. Replace with actual schema for Theme or Shortcut.
type IndividualConfig struct {

	Key string `json:"key"`

	Value string `json:"value"`

	// Property key from value object or empty string
	NameIndex string `json:"nameIndex"`

	Source Source `json:"source"`
}
