/*
 * Extension Config API
 *
 * API to submit and publish an ExtensionConfig object
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Extension struct {

	UserName string `json:"userName"`

	UserId string `json:"userId"`

	// this is a unique name of the package. On extension config, it is set to kebab-case of user's set name
	Name string `json:"name"`

	Config string `json:"config"`

	PackageJson string `json:"packageJson"`

	Id float32 `json:"id,omitempty"`
}
