/*
 * Extension Config API
 *
 * API to submit and publish an ExtensionConfig object
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Config - Generic configuration object. Replace with actual schema for Theme or Shortcut.
type Config struct {

	Key string `json:"key"`

	Value string `json:"value"`

	Label string `json:"label,omitempty"`
}
