/*
 * Extension Config API
 *
 * API to submit and publish an ExtensionConfig object
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateExtension201Response struct {

	Success bool `json:"success,omitempty"`

	// The ID of the created extension
	Id string `json:"id,omitempty"`
}
