/* tslint:disable */
/* eslint-disable */
/**
 * Extension Config API
 * API to submit and publish an ExtensionConfig object
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateExtensionConfig201Response,
  ExtensionConfig,
} from '../models/index';
import {
    CreateExtensionConfig201ResponseFromJSON,
    CreateExtensionConfig201ResponseToJSON,
    ExtensionConfigFromJSON,
    ExtensionConfigToJSON,
} from '../models/index';

export interface CreateExtensionConfigRequest {
    extensionConfig: ExtensionConfig;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Submit a new extension config
     */
    async createExtensionConfigRaw(requestParameters: CreateExtensionConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateExtensionConfig201Response>> {
        if (requestParameters['extensionConfig'] == null) {
            throw new runtime.RequiredError(
                'extensionConfig',
                'Required parameter "extensionConfig" was null or undefined when calling createExtensionConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/extensions`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExtensionConfigToJSON(requestParameters['extensionConfig']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateExtensionConfig201ResponseFromJSON(jsonValue));
    }

    /**
     * Submit a new extension config
     */
    async createExtensionConfig(requestParameters: CreateExtensionConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateExtensionConfig201Response> {
        const response = await this.createExtensionConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
